[package]
name = "gitrusted"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.1"
gtk = { version = "0.7.3", package = "gtk4", features = ["v4_12"] }
